### ISSUE TITLE
ERROR in Cannot find module 'less'

### ISSUE THREAD

**Issue by ByJC** [yankouskia/Agile-board#13]
Hi !

So I wanted to try your project which seems nice and I follow your instructions : 

```
npm install
npm run build
```

During the build webpack I got the following error : 

```
ERROR in Cannot find module 'less'
 @ ./app/client/style.less 4:14-122

ERROR in ./app/client/style.less
Module build failed: Error: Cannot find module 'less'
```

I try to install globally less but it didn't solve the issue.
Do you have any idea ?

**Comment by yankouskia** [comment]
Hi!
I checked one more time and it is ok. Could you please try to remove `less-loader` from your `node_modules` and reinstall? And what version of nodejs do you use (`node -v`)?
Thanks for issue.

**Comment by ByJC** [comment]
I did remove less-loader and npm install : 

```
agile-board@1.0.0 /Users/JC/Workspace/proto/Agile-board
├── UNMET PEER DEPENDENCY less@^2.3.1
└── less-loader@2.2.3

npm WARN less-loader@2.2.3 requires a peer of less@^2.3.1 but none was installed.
```

So I install locally `less` in the project and it works now.
I think you might need to add the less dependency to the package.json

For node, i'm with version 5.7.1

**Comment by yankouskia** [comment]
So, as I understood, you reinstalled `less-loader` and it is ok :+1: 
You don't need `less` here. You need just loader for such syntax in webpack. 
About less - I use library `bootstrap-less`

**Comment by ByJC** [comment]
> So, as I understood, you reinstalled less-loader and it is ok :+1: 

No, I reinstalled less-loader but I had to install less `npm install less` in the project too.
I understand you use less-loader for webpack but it use less as a peer dependencies and it failed to install it : 
`UNMET PEER DEPENDENCY less@^2.3.1`

**Comment by yankouskia** [comment]
You use `npm 3`, so it requires this peer dependency. I have updated `README.md`, that project for node version 4, and according to this, npm of second version.
But thanks for issue )
